# Generated by Django 2.2.3 on 2019-11-03 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=150, verbose_name='Autor')),
                ('comment_email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('comment', models.TextField(verbose_name='Comentário')),
                ('comment_creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('comment_published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('comment_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post', verbose_name='Post')),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
