# Generated by Django 2.2.3 on 2019-11-03 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=255, verbose_name='Título')),
                ('post_creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('post_content', models.TextField(verbose_name='Conteúdo')),
                ('post_summary', models.TextField(verbose_name='Resumo')),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='post_img/%Y/%m/%d', verbose_name='Imagem')),
                ('post_published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('post_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.Category', verbose_name='Categoria')),
            ],
        ),
    ]
